version: '2.1'
orbs:
  maven: circleci/maven@1.4.1
  maven-build: inclasstoday/maven-build@1.0.10
  qodana: jetbrains/qodana@2023.1
jobs:
  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
      - qodana/scan:
          args: -l jetbrains/qodana-jvm
  build:
    docker:
      - image: 'docker:latest'
    steps:
      - checkout
      - run:
          name: Build the application
          command: mvn clean install
  test:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn test
      - qodana/scan:
          args: -l jetbrains/qodana-jvm
  javadoc:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - run: mvn javadoc:javadoc
      - attach_workspace:
          at: ./docs
      - store_artifacts:
          path: ./docs
workflows:
  main:
    jobs:
      - code-quality:
          context: qodana
      - build
      - test:
          requires:
            - build
      - javadoc:
          requires:
            - build
      - maven/test
      - maven-build/docker_build
