version: '2.1'
orbs:
  maven: circleci/maven@1.4.1
  qodana: jetbrains/qodana@2023.1
jobs:
  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
      - qodana/scan:
          args: -l jetbrains/qodana-jvm
workflows:
  main:
    jobs:
      - code-quality:
          context: qodana
      - maven/test
