version: '2.1'
orbs:
  maven: circleci/maven@1.4.1
  qodana: jetbrains/qodana@2023.1
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=marton552_Nonogram_online
  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
      - qodana/scan:
          args: -l jetbrains/qodana-jvm
workflows:
  main:
    jobs:
      - build
      - code-quality:
          context: qodana
      - maven/test
